### ISSUE TITLE
Roll Command

### ISSUE THREAD

**Issue by noah-guillory** [Splyth/slack_bot#23]
Rolls one or more dice. Defaults to 1d6, max is 300d20.

**Comment by Shargon-Pendragon** [comment]
Hey I'm @Splyth brother. I got this.

**Comment by jedibob5** [comment]
I feel like we should at least go up to d100, that's a relatively common roll in many TTRPGs. I don't think rolling 300d100 would cause any major performance troubles but I can test that before we merge.

**Comment by Splyth** [comment]
Python 2 has a max int size of 9223372036854775807

Unsure about Python 3. So there's no real danger. That description was copied over from the old
devoops commands. We can roll 1000d1000 if wanted.

I think the hope was Phaye would actually make some emojis so this looks a little fancier. But that can be a different Issue.
