### ISSUE TITLE
Forward all unsupported commands to a chat bot api

### ISSUE THREAD

**Issue by Mill1893** [Splyth/slack_bot#43]
Similar to Lilly, forward all non commands to a chat bot api, if that returns nothing then return our default not found response

**Comment by jedibob5** [comment]
If we _really_ want to do this again, it must be limited to #bot_spam _only_.

**Comment by Mill1893** [comment]
I'm honestly not convinced that we want this functionality, but it was requested to be logged as an issue so I figured we could talk about it

**Comment by Splyth** [comment]
I'm not really in favor of this one. Bot Spam isn't an active enough channel to warrant it. And as fun as goofy comments are they can really pollute a channel fast.

Just my 2 cents.

**Comment by Mill1893** [comment]
Something else to consider is I haven't found a chat bot we could hit with a free tier. The cheapest I've found is CleverBot, which has a PAYG model for $20 for 15k requests. Not bad, but still. A feature we're not sure we want that'll cost money isn't looking great.
